IRODS_SERVER_HOST = "localhost"
IRODS_SERVER_PORT = "1247"
IRODS_SERVER_ZONE = "tempZone"
IRODS_SERVER_DN = ""
IRODS_USER_USERNAME = "rods"
IRODS_USER_PASSWORD = "rods"
IRODS_AUTHENTICATION_SCHEME = "gsi"
IRODS_SERVER_VERSION = (4, 2, 0)
