# This action is based on Github's default starter workflow for Python at
# https://github.com/actions/starter-workflows/blob/master/ci/python-package.yml
# (C) Github, MIT License

name: "Python type checking"

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-24.04

    strategy:
      matrix:
        python-version: ['3.9']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install ./
        pip install mypy==1.16.1

    - name: Run type checks
      run: |
        mypy --ignore-missing-imports irods

